### ISSUE TITLE
[doc]: Spelling error in the doc

### ISSUE THREAD

**Issue by AnkitKumarvaid** [keploy/samples-java#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![spelling error](https://user-images.githubusercontent.com/61087993/196002528-548cba03-e909-40d2-91f3-0fb115e6f0cb.png)

### Steps to reproduce

Correct the spelling  of the response

### Version

Cloud

**Comment by gouravkrosx** [comment]
closes with #32
